name: "Build and Release"
inputs:
  token:
    description: "A Github token"
    required: true
  build-tool:
    description: "maven | npm"
    required: true
  settings-url:
    description: "URL to settings.xml file"
    required: false
  with-storybook:
    description: "true | false"
    required: false
  skip-tests:
    description: "true | false"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: gustavogarayalde/github-actions/actions/build/maven@v0.0.11
      name: Maven Build
      if: ${{ inputs.build-tool == 'maven'}}
      with:
        settings-url: ${{ inputs.settings-url }}
        token: ${{ inputs.token }}

    - uses: gustavogarayalde/github-actions/actions/build/npm@v0.0.11
      name: NPM Build
      if: ${{ inputs.build-tool == 'npm'}}
      with:
        app-type: ${{ inputs.app-type }}
        token: ${{ inputs.token }}
        with-storybook: ${{ inputs.with-storybook }}
        skip-tests: ${{ inputs.skip-tests }}

    - name: Git Config
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - uses: actions/checkout@v3
      if: ${{ inputs.app-type == 'npm-ui-lib' }}
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: gustavogarayalde/github-actions/actions/release/maven@v0.0.11
      name: Maven Release
      if: ${{ inputs.build-tool == 'maven'}}
      with:
        token: ${{ github.token }}

    - uses: gustavogarayalde/github-actions/actions/release/npm@v0.0.11
      name: NPM Release
      if: ${{ inputs.build-tool == 'npm'}}

    - name: Push version bump to repo
      shell: bash
      run: git push

    - uses: actions/checkout@v3
      name: Checkout prepare push tag
      with:
        token: ${{ inputs.token }}
        clean: "false"

    - name: Push tag
      shell: bash
      run: git push --tags
